# Generated by Django 5.1.6 on 2025-02-11 21:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Jogador',
            fields=[
                ('id_jogador', models.AutoField(primary_key=True, serialize=False)),
                ('jogador', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Jogo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gols_flu', models.IntegerField()),
                ('gols_adv', models.IntegerField()),
                ('adversario', models.CharField(max_length=100)),
                ('local_adv', models.CharField(max_length=3)),
                ('estadio', models.CharField(max_length=100)),
                ('local_estadio', models.CharField(max_length=3)),
                ('data', models.DateField()),
                ('resultado', models.CharField(max_length=5)),
                ('campeonato', models.CharField(max_length=100)),
                ('arbitro', models.CharField(max_length=100)),
                ('publico', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Gol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('autor_gol', models.CharField(max_length=100)),
                ('assistencia', models.CharField(blank=True, max_length=100, null=True)),
                ('id_ass', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='autor_assist', to='meus_jogos_app.jogador')),
                ('id_autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='autor_gol', to='meus_jogos_app.jogador')),
                ('id_jogo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meus_jogos_app.jogo')),
            ],
        ),
        migrations.CreateModel(
            name='Escalacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jogador', models.CharField(max_length=100)),
                ('id_jogador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meus_jogos_app.jogador')),
                ('id_jogo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meus_jogos_app.jogo')),
            ],
        ),
    ]
