# Generated by Django 5.1.6 on 2025-02-16 04:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meus_jogos_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OutrosJogos',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('mandante', models.CharField(max_length=100)),
                ('gols_mandante', models.IntegerField()),
                ('gols_visitante', models.IntegerField()),
                ('adversario', models.CharField(max_length=100)),
                ('estadio', models.CharField(max_length=100)),
                ('local_estadio', models.CharField(max_length=100)),
                ('data', models.DateField()),
                ('campeonato', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='gol',
            name='id_jogo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gols', to='meus_jogos_app.jogo'),
        ),
    ]
