# Generated by Django 5.1.6 on 2025-02-16 04:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meus_jogos_app', '0002_outrosjogos_alter_gol_id_jogo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='outrosjogos',
            old_name='adversario',
            new_name='visitante',
        ),
    ]
