# Generated by Django 5.1.6 on 2025-02-17 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meus_jogos_app', '0003_rename_adversario_outrosjogos_visitante'),
    ]

    operations = [
        migrations.AddField(
            model_name='gol',
            name='id_gol',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
