# Generated by Django 5.1.6 on 2025-02-17 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meus_jogos_app', '0004_gol_id_gol'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gol',
            name='id',
        ),
        migrations.AlterField(
            model_name='gol',
            name='id_gol',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
