# Generated by Django 5.1.6 on 2025-02-17 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meus_jogos_app', '0005_remove_gol_id_alter_gol_id_gol'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gol',
            name='id_gol',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
